### ISSUE TITLE
test

### ISSUE THREAD

**Issue by JanKoelzer** [JanKoelzer/reactive-async#29]
test("whenNext: concurrent put next") {
    var expectedValue: Option[Immutability] = None

    for (_ <- 1 to 100) {
      implicit val pool = new HandlerPool
      val completer1 = CellCompleter[ImmutabilityKey.type, Immutability](ImmutabilityKey)
      val completer2 = CellCompleter[ImmutabilityKey.type, Immutability](ImmutabilityKey)

      val cell1 = completer1.cell

      pool.execute(() => cell1.whenNext(completer2.cell, x => {
        if (x.get == Mutable) NextOutcome(Mutable)
        else NoOutcome
      }))
      pool.execute(() => completer2.putNext(Mutable))

      val fut = pool.quiescentResolveDefaults
      Await.ready(fut, 2.seconds)

      if (expectedValue.isEmpty) expectedValue = Some(cell1.getResult())
      else assert(cell1.getResult() == expectedValue.get)

      pool.shutdown()
    }
  }

- whenNext: concurrent put next *** FAILED ***
[info]   java.util.concurrent.TimeoutException: Futures timed out after [2 seconds]
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:255)
[info]   at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:183)
[info]   at scala.concurrent.Await$.$anonfun$ready$1(package.scala:191)
[info]   at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[info]   at scala.concurrent.Await$.ready(package.scala:142)
[info]   at com.phaller.rasync.test.BaseSuite.$anonfun$new$108(base.scala:870)
[info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:156)
[info]   at com.phaller.rasync.test.BaseSuite.$anonfun$new$107(base.scala:856)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   ...

**Comment by JanKoelzer** [comment]
This can be fixed by increasing duration of Await.ready(…)
So this is not a bug of RA but due to slow hardware.
